import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"

export function AdminCredits() {
  return (
    <div className="space-y-6">
      <Card className="bg-gray-900/60 border-purple-500/20 shadow-lg">
        <CardHeader className="text-center">
          <CardTitle className="text-2xl">Credits</CardTitle>
          <CardDescription>The people behind WebInject 2.0 Admin Panel</CardDescription>
        </CardHeader>
        <CardContent className="flex flex-col items-center justify-center space-y-8 py-8">
          <div className="w-32 h-32 rounded-full bg-gradient-to-br from-purple-500 to-cyan-500 flex items-center justify-center text-white text-4xl font-bold shadow-lg">
            K
          </div>

          <div className="text-center space-y-2">
            <h3 className="text-xl font-bold text-white">Made by Kai</h3>
            <p className="text-gray-400">UI and code generated by v0.dev</p>
          </div>

          <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mt-8 w-full max-w-2xl">
            <div className="flex flex-col items-center p-4 rounded-lg bg-gray-800/50 border border-gray-800">
              <div className="text-2xl font-bold text-white">UI</div>
              <div className="text-sm text-gray-400">Design</div>
            </div>

            <div className="flex flex-col items-center p-4 rounded-lg bg-gray-800/50 border border-gray-800">
              <div className="text-2xl font-bold text-white">UX</div>
              <div className="text-sm text-gray-400">Experience</div>
            </div>

            <div className="flex flex-col items-center p-4 rounded-lg bg-gray-800/50 border border-gray-800">
              <div className="text-2xl font-bold text-white">Code</div>
              <div className="text-sm text-gray-400">Development</div>
            </div>

            <div className="flex flex-col items-center p-4 rounded-lg bg-gray-800/50 border border-gray-800">
              <div className="text-2xl font-bold text-white">v0</div>
              <div className="text-sm text-gray-400">Generation</div>
            </div>
          </div>

          <div className="flex flex-wrap justify-center gap-2 mt-6">
            <Badge variant="outline" className="bg-purple-500/10 text-purple-500 border-purple-500/20">
              React
            </Badge>
            <Badge variant="outline" className="bg-cyan-500/10 text-cyan-500 border-cyan-500/20">
              Next.js
            </Badge>
            <Badge variant="outline" className="bg-blue-500/10 text-blue-500 border-blue-500/20">
              Tailwind CSS
            </Badge>
            <Badge variant="outline" className="bg-green-500/10 text-green-500 border-green-500/20">
              shadcn/ui
            </Badge>
            <Badge variant="outline" className="bg-yellow-500/10 text-yellow-500 border-yellow-500/20">
              TypeScript
            </Badge>
          </div>

          <div className="text-center text-sm text-gray-400 mt-8">
            <p>WebInject 2.0 Admin Panel v1.0.0</p>
            <p>© 2023 All Rights Reserved</p>
          </div>
        </CardContent>
      </Card>
    </div>
  )
}
