// Centralized game catalog with metadata for consistent use across the site
export interface Game {
  id: string
  name: string
  description: string
  category: "competitive" | "casual" | "rpg" | "adventure" | "strategy"
  popularity: "trending" | "featured" | "recent" | "standard"
  status: "available" | "coming-soon" | "experimental"
  image: string
  color: string
  href: string
  tags: string[]
  modsCount?: number
  downloadsCount?: number
  rating?: number
}

export const GAMES: Game[] = [
  {
    id: "minecraft",
    name: "Minecraft",
    description: "Enhance your Minecraft experience with powerful client mods and enhancements",
    category: "casual",
    popularity: "trending",
    status: "available",
    image: "/images/minecraft-card.jpg",
    color: "green",
    href: "/games/minecraft",
    tags: ["sandbox", "creative", "modding"],
    modsCount: 1250,
    downloadsCount: 45000,
    rating: 4.8,
  },
  {
    id: "roblox",
    name: "Roblox",
    description: "Unlock new possibilities in Roblox with powerful tweaks and enhancements",
    category: "casual",
    popularity: "featured",
    status: "available",
    image: "/images/roblox-card.jpg",
    color: "blue",
    href: "/games/roblox",
    tags: ["social", "creative", "multiplayer"],
    modsCount: 890,
    downloadsCount: 38000,
    rating: 4.6,
  },
  {
    id: "fortnite",
    name: "Fortnite",
    description: "Gain the competitive edge in Fortnite with advanced tools and mods",
    category: "competitive",
    popularity: "trending",
    status: "available",
    image: "/images/fortnite-card.jpg",
    color: "purple",
    href: "/games/fortnite",
    tags: ["battle-royale", "pvp", "competitive"],
    modsCount: 520,
    downloadsCount: 62000,
    rating: 4.5,
  },
  {
    id: "gtav",
    name: "GTA V",
    description: "Transform your GTA V experience with powerful mods and customizations",
    category: "adventure",
    popularity: "featured",
    status: "available",
    image: "/images/gtav-card.jpg",
    color: "red",
    href: "/games/gtav",
    tags: ["open-world", "action", "multiplayer"],
    modsCount: 2100,
    downloadsCount: 95000,
    rating: 4.9,
  },
  {
    id: "valorant",
    name: "Valorant",
    description: "Enhance your Valorant gameplay with advanced tactical tools",
    category: "competitive",
    popularity: "trending",
    status: "available",
    image: "/images/valorant-card.jpg",
    color: "pink",
    href: "/games/valorant",
    tags: ["tactical", "fps", "competitive"],
    modsCount: 340,
    downloadsCount: 51000,
    rating: 4.7,
  },
  {
    id: "cs2",
    name: "CS2",
    description: "Dominate in Counter-Strike 2 with powerful competitive tools",
    category: "competitive",
    popularity: "trending",
    status: "available",
    image: "/images/cs2-card.jpg",
    color: "orange",
    href: "/games/cs2",
    tags: ["tactical", "fps", "esports"],
    modsCount: 680,
    downloadsCount: 72000,
    rating: 4.8,
  },
  {
    id: "cod",
    name: "Modern Warfare II",
    description: "Master your CoD gameplay with specialized modifications",
    category: "competitive",
    popularity: "featured",
    status: "available",
    image: "/images/cod-card.jpg",
    color: "gray",
    href: "/games/cod",
    tags: ["fps", "action", "multiplayer"],
    modsCount: 420,
    downloadsCount: 58000,
    rating: 4.6,
  },
  {
    id: "apex",
    name: "Apex Legends",
    description: "Dominate the arena with cutting-edge Apex Legends mods",
    category: "competitive",
    popularity: "featured",
    status: "available",
    image: "/images/apex-card.jpg",
    color: "red",
    href: "/games/apex",
    tags: ["battle-royale", "fps", "competitive"],
    modsCount: 310,
    downloadsCount: 44000,
    rating: 4.5,
  },
  {
    id: "overwatch",
    name: "Overwatch 2",
    description: "Take your Overwatch skills to the next level with custom tools",
    category: "competitive",
    popularity: "standard",
    status: "available",
    image: "/images/overwatch-card.jpg",
    color: "blue",
    href: "/games/overwatch",
    tags: ["team-based", "fps", "competitive"],
    modsCount: 280,
    downloadsCount: 35000,
    rating: 4.4,
  },
  {
    id: "rainbow",
    name: "Rainbow Six Siege",
    description: "Tactical advantage with premium Rainbow Six Siege mods",
    category: "competitive",
    popularity: "standard",
    status: "available",
    image: "/images/rainbow-card.jpg",
    color: "amber",
    href: "/games/rainbow",
    tags: ["tactical", "fps", "team-based"],
    modsCount: 195,
    downloadsCount: 29000,
    rating: 4.3,
  },
  {
    id: "battlefield",
    name: "Battlefield 2042",
    description: "Conquer the battlefield with these game-changing mods",
    category: "competitive",
    popularity: "standard",
    status: "available",
    image: "/images/battlefield-card.jpg",
    color: "blue",
    href: "/games/battlefield",
    tags: ["fps", "large-scale", "vehicles"],
    modsCount: 420,
    downloadsCount: 41000,
    rating: 4.5,
  },
  {
    id: "tarkov",
    name: "Escape from Tarkov",
    description: "Survive and thrive with these essential Tarkov tools",
    category: "adventure",
    popularity: "recent",
    status: "available",
    image: "/images/tarkov-card.jpg",
    color: "stone",
    href: "/games/tarkov",
    tags: ["hardcore", "survival", "multiplayer"],
    modsCount: 230,
    downloadsCount: 18000,
    rating: 4.6,
  },
  {
    id: "pubg",
    name: "PUBG: Battlegrounds",
    description: "Get the winning edge in PUBG with premium mods",
    category: "competitive",
    popularity: "recent",
    status: "available",
    image: "/images/pubg-card.jpg",
    color: "yellow",
    href: "/games/pubg",
    tags: ["battle-royale", "large-scale", "pvp"],
    modsCount: 350,
    downloadsCount: 33000,
    rating: 4.5,
  },
  {
    id: "halo",
    name: "Halo Infinite",
    description: "Elevate your Spartan with advanced Halo mods",
    category: "competitive",
    popularity: "standard",
    status: "available",
    image: "/images/halo-card.jpg",
    color: "green",
    href: "/games/halo",
    tags: ["sci-fi", "fps", "competitive"],
    modsCount: 290,
    downloadsCount: 27000,
    rating: 4.4,
  },
  {
    id: "halflife",
    name: "Half-Life 2",
    description: "Revolutionize the classic with Half-Life 2 mods",
    category: "adventure",
    popularity: "standard",
    status: "available",
    image: "/images/halflife-card.jpg",
    color: "orange",
    href: "/games/halflife",
    tags: ["classic", "fps", "story-driven"],
    modsCount: 780,
    downloadsCount: 22000,
    rating: 4.7,
  },
  {
    id: "doom",
    name: "DOOM Eternal",
    description: "Rip and tear even better with our DOOM Eternal enhancements",
    category: "adventure",
    popularity: "standard",
    status: "available",
    image: "/images/doom-card.jpg",
    color: "red",
    href: "/games/doom",
    tags: ["action", "fast-paced", "difficult"],
    modsCount: 420,
    downloadsCount: 19000,
    rating: 4.6,
  },
  {
    id: "tf2",
    name: "Team Fortress 2",
    description: "Dominate any class with these TF2 mods and tools",
    category: "competitive",
    popularity: "recent",
    status: "available",
    image: "/images/tf2-card.jpg",
    color: "red",
    href: "/games/tf2",
    tags: ["team-based", "fps", "free-to-play"],
    modsCount: 310,
    downloadsCount: 16000,
    rating: 4.5,
  },
  {
    id: "quake",
    name: "Quake Champions",
    description: "Enhance your fragging ability with Quake Champions mods",
    category: "competitive",
    popularity: "standard",
    status: "available",
    image: "/images/quake-card.jpg",
    color: "purple",
    href: "/games/quake",
    tags: ["classic", "fps", "competitive"],
    modsCount: 180,
    downloadsCount: 12000,
    rating: 4.4,
  },
  {
    id: "l4d2",
    name: "Left 4 Dead 2",
    description: "Survive the zombie apocalypse with essential L4D2 tools",
    category: "adventure",
    popularity: "standard",
    status: "available",
    image: "/images/l4d2-card.jpg",
    color: "red",
    href: "/games/l4d2",
    tags: ["co-op", "horror", "classic"],
    modsCount: 560,
    downloadsCount: 14000,
    rating: 4.5,
  },
  {
    id: "farcry",
    name: "Far Cry 3",
    description: "Master the island with Far Cry 3 enhancement mods",
    category: "adventure",
    popularity: "standard",
    status: "available",
    image: "/images/farcry-card.jpg",
    color: "blue",
    href: "/games/farcry",
    tags: ["open-world", "action", "adventure"],
    modsCount: 320,
    downloadsCount: 17000,
    rating: 4.5,
  },
  {
    id: "borderlands",
    name: "Borderlands 2",
    description: "Loot and shoot even better with Borderlands 2 mods",
    category: "adventure",
    popularity: "standard",
    status: "available",
    image: "/images/borderlands-card.jpg",
    color: "yellow",
    href: "/games/borderlands",
    tags: ["looter-shooter", "action", "co-op"],
    modsCount: 480,
    downloadsCount: 21000,
    rating: 4.6,
  },
  {
    id: "metro",
    name: "Metro Exodus",
    description: "Survive the wasteland with Metro Exodus enhancements",
    category: "adventure",
    popularity: "standard",
    status: "available",
    image: "/images/metro-card.jpg",
    color: "stone",
    href: "/games/metro",
    tags: ["story-driven", "survival", "atmospheric"],
    modsCount: 220,
    downloadsCount: 11000,
    rating: 4.5,
  },
  {
    id: "callofjuarez",
    name: "Call of Juarez: Gunslinger",
    description: "Become a legendary gunslinger with western-themed mods",
    category: "adventure",
    popularity: "standard",
    status: "available",
    image: "/images/callofjuarez-card.jpg",
    color: "amber",
    href: "/games/callofjuarez",
    tags: ["western", "action", "story-driven"],
    modsCount: 150,
    downloadsCount: 8000,
    rating: 4.4,
  },
  {
    id: "titanfall",
    name: "Titanfall 2",
    description: "Elevate your pilot and titan skills with premium mods",
    category: "competitive",
    popularity: "standard",
    status: "available",
    image: "/images/titanfall-card.jpg",
    color: "blue",
    href: "/games/titanfall",
    tags: ["fps", "fast-paced", "mech-based"],
    modsCount: 260,
    downloadsCount: 15000,
    rating: 4.5,
  },
]

export function getGameById(id: string): Game | undefined {
  return GAMES.find((g) => g.id === id)
}

export function getGamesByCategory(category: Game["category"]): Game[] {
  return GAMES.filter((g) => g.category === category)
}

export function getGamesByPopularity(popularity: Game["popularity"]): Game[] {
  return GAMES.filter((g) => g.popularity === popularity)
}

export function getTrendingGames(limit: number = 6): Game[] {
  return GAMES.filter((g) => g.popularity === "trending").slice(0, limit)
}

export function getFeaturedGames(limit: number = 8): Game[] {
  return GAMES.filter((g) => g.status === "available").slice(0, limit)
}

export function getRecentGames(limit: number = 6): Game[] {
  return GAMES.filter((g) => g.popularity === "recent").slice(0, limit)
}

export function searchGames(query: string): Game[] {
  const q = query.toLowerCase()
  return GAMES.filter(
    (g) =>
      g.name.toLowerCase().includes(q) ||
      g.description.toLowerCase().includes(q) ||
      g.tags.some((tag) => tag.toLowerCase().includes(q)),
  )
}
